### PR TITLE
chore: pause emit pause reason

### PR DESCRIPTION
**Pull request by asdfryan**

### CODE REVIEW

**Review by lucasmarshall — CHANGES_REQUESTED** [review]
I don't see where we are setting the pause reason for manual pauses. Can we add that?

**Comment by asdfryan** [comment]
> I don't see where we are setting the pause reason for manual pauses. Can we add that?

The way @tomkit implemented this, the notification / email path is only triggered for autopaused workflows. Doing this would require a much more significant change. (I agree with you though)

**Comment by lucasmarshall** [comment]
> > I don't see where we are setting the pause reason for manual pauses. Can we add that?
> 
> The way @tomkit implemented this, the notification / email path is only triggered for autopaused workflows. Doing this would require a much more significant change. (I agree with you though)

We do send webhooks on manual pauses though. It would be good to have the reason there. (That's what's powering the slack notifications)

**Comment by asdfryan** [comment]
> > > I don't see where we are setting the pause reason for manual pauses. Can we add that?
> > 
> > 
> > The way @tomkit implemented this, the notification / email path is only triggered for autopaused workflows. Doing this would require a much more significant change. (I agree with you though)
> 
> We do send webhooks on manual pauses though. It would be good to have the reason there. (That's what's powering the slack notifications)

Done.

**Review by lucasmarshall — APPROVED** [review]

**Pull request merged**
