### PR TITLE
feat: rewrite custom field keys & values in both directions for pipedrive

### PR DESCRIPTION
**Pull request by albertyfwu**
## Test Plan

[Describe test plan here]

## Deployment instructions

[Add any special deployment instructions here]

### CODE REVIEW

**Review by asdfryan — CHANGES_REQUESTED** [review]
Where are we applying the schema fields for pipedrive? I think in order to support custom fields, we need to do that first, no?

**Comment by albertyfwu** [comment]
> Where are we applying the schema fields for pipedrive? I think in order to support custom fields, we need to do that first, no?

yea didn't realize it's not implemented, though i would say it's orthogonal to this PR.

can we get this in first?

would prefer not to make massive PRs if not necessary

**Review by asdfryan — COMMENTED** [review]
Is there any type coercion necessary? Does this work with non-string custom fields (i.e. integer or boolean)?

**Comment by albertyfwu** [comment]
> Is there any type coercion necessary? Does this work with non-string custom fields (i.e. integer or boolean)?

not sure but i think that's not supaglue's responsibility

**Review by asdfryan — APPROVED** [review]

**Pull request merged**
